name: Test Application

on:
    pull_request:
    push:
        branches:
            - master

jobs:
    php:
        name: PHP
        runs-on: ubuntu-latest

        services:
            mysql:
                image: mysql:5.7
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
                ports:
                    - 3306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        steps:
            - name: Checkout project
              uses: actions/checkout@v2

            - name: Install and configure PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.0'
                  extensions: ctype, iconv, mysql
                  coverage: none
                  tools: composer

            - name: Install composer dependencies
              uses: ramsey/composer-install@v1

            - name: Lint code
              run: |
                  bin/adminconsole doctrine:database:create --if-not-exists
                  bin/adminconsole doctrine:schema:update --force
                  composer lint

            - name: Execute test cases
              run: |
                  composer bootstrap-test-environment
                  composer test

            - name: Test project initialization
              run: bin/console sulu:build dev --destroy
