name: Test Application

on:
    pull_request:
    push:
        branches:
            - master

jobs:
    php:
        name: PHP
        runs-on: ubuntu-latest

        services:
            mysql:
                image: mysql:8.0
                env:
                    MYSQL_ROOT_PASSWORD: root
                ports:
                    - 3306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        steps:
            - name: Checkout project
              uses: actions/checkout@v2

            - name: Install and configure PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.1'
                  extensions: ctype, iconv, mysql
                  coverage: none
                  tools: composer

            - name: Install composer dependencies
              uses: ramsey/composer-install@v1

            - name: Lint code
              run: composer lint

            - name: Bootstrap test environment
              run: composer bootstrap-test-environment

            - name: Execute test cases
              run: composer test

            - name: Test project initialization
              run: bin/console sulu:build dev --destroy
